### ISSUE TITLE
Docs link in the NPM README is broken

### ISSUE THREAD

**Issue by RezaRahemtola** [gnolang/gno-js-client#127]
The documentation link in the README of the [NPM package](https://www.npmjs.com/package/@gnolang/gno-js-client) points to
https://onbloc.gitbook.io/gnoland-developer-portal/docs/gno-js-client
which redirects to
https://docs.gno.land/docs/gno-js-client (404)

It should be https://docs.gno.land/reference/gno-js-client as in the README of this repository, should be solved automatically with the next package publish

**Comment by leohhhn** [comment]
Was fixed.
