### ISSUE TITLE
Are there RPC endpoints for test3.gno.land?

### ISSUE THREAD

**Issue by grepsuzette** [gnolang/gno-js-client#85]
There would be a lot of interesting experimentations (leading to many use cases) if that was the case,
but for now I can only use this locally. 

That lib is sooo where web3 is. It needs some endpoints!

**Comment by grepsuzette** [comment]
Think it must be on test3.gno.land tcp port 36657

**Comment by zivkovicmilos** [comment]
cc @albttx

The RPC URL for test3 should be:
`http://test3.gno.land:36657`

with the WS endpoint being:
`ws://test3.gno.land:36657/websocket`

**Comment by albttx** [comment]
You should use https://rpc.test3.gno.land/ 

so `https://rpc.test3.gno.land:443` in config

**Comment by zivkovicmilos** [comment]
Thank you @albttx 🙏 

Closing this issue for now
